<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
  	<PackageReference Include="FluentAssertions" />
  	<PackageReference Include="Microsoft.NET.Test.Sdk" />
  	<PackageReference Include="NetArchTest.Rules" />
  	<PackageReference Include="xunit" />
  	<PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bootstrapper\Web.Api\Web.Api.csproj" />
    <ProjectReference Include="..\..\src\Core\Application\Application.csproj" />
    <ProjectReference Include="..\..\src\Core\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\src\External\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\External\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\..\src\External\Presentation\Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>